/* Generated by npm run sync-config — edit .env, not this file */
window.__SITE_CONFIG__ = {
  "productName": "SQLinq",
  "productTagline": "Free SQL to LINQ for Visual Studio and VS Code",
  "productPhase": "Phase 1 — Microsoft SQL Server · Visual Studio · VS Code",
  "sinceDate": "2026-01-12",
  "githubOwner": "nuthanm",
  "githubRepo": "SQLinq",
  "githubUrl": "https://github.com/nuthanm/SQLinq",
  "siteUrl": "https://sqlinq.vercel.app",
  "apiBaseUrl": "https://sqlinq.vercel.app",
  "siteDescription": "Convert any SQL to idiomatic LINQ inside your IDE — free forever, extensible dialect architecture.",
  "creditsText": "Independent SQL to LINQ tooling for Visual Studio and VS Code.",
  "faviconPath": "assets/favicon.svg?v=2"
};
