import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const envPath = path.join(root, ".env");
const examplePath = path.join(root, ".env.example");
const outPath = path.join(root, "js", "site-config.js");

function parseEnv(text) {
  const out = {};
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const i = line.indexOf("=");
    if (i === -1) continue;
    const key = line.slice(0, i).trim();
    let value = line.slice(i + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

const source = fs.existsSync(envPath) ? envPath : examplePath;
if (!fs.existsSync(source)) {
  console.error("Missing .env and .env.example");
  process.exit(1);
}

const env = parseEnv(fs.readFileSync(source, "utf8"));
const required = [
  "PRODUCT_NAME",
  "PRODUCT_TAGLINE",
  "PRODUCT_PHASE",
  "PRODUCT_SINCE_DATE",
  "GITHUB_OWNER",
  "GITHUB_REPO",
  "GITHUB_URL",
  "SITE_DESCRIPTION",
  "CREDITS_TEXT",
];

for (const key of required) {
  if (!env[key]) {
    console.error(`Missing ${key} in ${path.basename(source)}`);
    process.exit(1);
  }
}

const config = {
  productName: env.PRODUCT_NAME,
  productTagline: env.PRODUCT_TAGLINE,
  productPhase: env.PRODUCT_PHASE,
  sinceDate: env.PRODUCT_SINCE_DATE,
  githubOwner: env.GITHUB_OWNER,
  githubRepo: env.GITHUB_REPO,
  githubUrl: env.GITHUB_URL,
  siteUrl: env.SITE_URL || "",
  siteDescription: env.SITE_DESCRIPTION,
  creditsText: env.CREDITS_TEXT,
};

fs.mkdirSync(path.dirname(outPath), { recursive: true });
const banner = `/* Generated by npm run sync-config — edit .env, not this file */\n`;
const body = `window.__SITE_CONFIG__ = ${JSON.stringify(config, null, 2)};\n`;
fs.writeFileSync(outPath, banner + body, "utf8");
console.log(`Wrote ${path.relative(root, outPath)} from ${path.basename(source)}`);
console.log(`Product name: ${config.productName}`);
